services:
  frontend:
    build:
      context: ./chame-gas-front
      dockerfile: Dockerfile
    container_name: chame-gas-frontend
    ports:
      - "80:80"
    networks:
      - chame-gas-network

networks:
  chame-gas-network:
    driver: bridge
